<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>CydPinballCards</AssemblyName>
    <RootNamespace>CydPinballCards</RootNamespace>
    <OutputType>Library</OutputType>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Unbroken.LaunchBox.Plugins">
      <HintPath>C:\Users\fcrews\LaunchBox\Core\Unbroken.LaunchBox.Plugins.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
