"""Generate firmware/src/wifi_secrets.h from firmware/wifi.json.

Copy firmware/wifi.example.json to firmware/wifi.json. That file is gitignored.
The SSID and password are compiled into the firmware and are not committed.
"""
from __future__ import annotations

import json
from pathlib import Path

HEADER = """\
#pragma once
// Generated by firmware/gen_wifi_secrets.py from firmware/wifi.json (gitignored).
// Do not commit this file. Empty WIFI_CFG_SSID disables Wi-Fi.
#define WIFI_CFG_SSID {ssid}
#define WIFI_CFG_PASS {password}
#define WIFI_CFG_HOST {host}
#define WIFI_CFG_PORT {port}
"""


def c_string(value: str) -> str:
    out = ['"']
    for ch in value:
        o = ord(ch)
        if ch in "\\\"":
            out.append("\\" + ch)
        elif 32 <= o < 127:
            out.append(ch)
        else:
            out.append("\\%03o" % o)
    out.append('"')
    return "".join(out)


def load_wifi(project_dir: Path) -> dict:
    path = project_dir / "wifi.json"
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        print("wifi.json ignored (%s); Wi-Fi disabled" % type(exc).__name__)
        return {}
    if not isinstance(data, dict):
        print("wifi.json ignored (not an object); Wi-Fi disabled")
        return {}
    return data


def render(data: dict) -> str:
    try:
        port = int(data.get("port") or 47311)
    except (TypeError, ValueError):
        port = 47311
    port = min(65535, max(1, port))
    return HEADER.format(
        ssid=c_string(str(data.get("ssid") or "")),
        password=c_string(str(data.get("pass") or "")),
        host=c_string(str(data.get("host") or "")),
        port=port,
    )


def generate(project_dir: Path) -> Path:
    project_dir = Path(project_dir)
    text = render(load_wifi(project_dir))
    out = project_dir / "src" / "wifi_secrets.h"
    out.parent.mkdir(parents=True, exist_ok=True)
    if not out.is_file() or out.read_text(encoding="utf-8") != text:
        out.write_text(text, encoding="utf-8", newline="\n")
        present = "set" if 'WIFI_CFG_SSID ""' not in text else "empty"
        print("wifi_secrets.h updated (ssid %s)" % present)
    return out


try:
    Import("env")  # PlatformIO SCons
except Exception:
    env = None

if env is not None:
    generate(env["PROJECT_DIR"])